### ISSUE TITLE
missing documentation for setting up the service from scratch

### ISSUE THREAD

**Issue by tobiasko** [wilhelm-lab/dlomix-serving#14]
Hi everyone,

let's try to collect **all** information that is need by people that want to setup a service instance (server) from scratch. Where should we collect the info? We should try to document all **required** steps starting from a specific std. platform (we are now starting from the Debian 11 distribution). Include checkpoints for stuff like GPU drivers etc., docker, python libs, ...

Best,
Tobi

**Comment by tkschmidt** [comment]
Hi @tobiasko,

I would recomment to not start with Debian. The installation of GPU drivers is always painful and we always use ubuntu servers in combination with the provided [lambdastack](https://lambdalabs.com/lambda-stack-deep-learning-software) of lambdalabs.

You can try to make it also work on Debian, but between figuring out the correct driver for NVIDA + CUDNN + kernel is a pain in the butt, and we use this wrapper for ubuntu for it.

Best,

Tobi

**Comment by tkschmidt** [comment]
I can provide a minimal ansible script to automatize it if you want it

**Comment by tkschmidt** [comment]
@tobiasko Please check https://github.com/wilhelm-lab/dlomix-serving/pull/19 . What else would you require as information?

**Comment by tobiasko** [comment]
@tkschmidt I will have a look! Should I ask our sys admin to give input? He did the painful job of installing the GPU drivers etc.

**Comment by tobiasko** [comment]
And he was successful using Debian 11. ;-)

**Comment by tkschmidt** [comment]
I'm happy to here that it worked out for him. Please provide his installation guide after https://github.com/wilhelm-lab/dlomix-serving/pull/19 is merged

**Comment by tobiasko** [comment]
okidoki!
